apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stalwart-mail-server.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stalwart-mail-server.labels" . | nindent 4 }}
data:
  config.toml: |
{{ include "stalwart-mail-server.configuration" . | indent 4 }}

---
{{- if .Values.security.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "stalwart-mail-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stalwart-mail-server.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "stalwart-mail-server.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  {{- include "stalwart-mail-server.networkPolicyRules" . | nindent 2 }}
{{- if .Values.security.networkPolicies.custom }}
{{- range .Values.security.networkPolicies.custom }}
---
{{- toYaml . }}
{{- end }}
{{- end }}
{{- end }}

---
{{- if .Values.security.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stalwart-mail-server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stalwart-mail-server.labels" . | nindent 4 }}
  {{- with .Values.security.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.security.serviceAccount.automountServiceAccountToken }}
{{- end }}

---
{{- if .Values.security.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "stalwart-mail-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stalwart-mail-server.labels" . | nindent 4 }}
rules:
# Minimal RBAC permissions for Stalwart
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
{{- if .Values.security.rbac.rules }}
{{- toYaml .Values.security.rbac.rules | nindent 0 }}
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "stalwart-mail-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stalwart-mail-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "stalwart-mail-server.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "stalwart-mail-server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}

---
{{- if .Values.stalwart.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "stalwart-mail-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stalwart-mail-server.labels" . | nindent 4 }}
spec:
  {{- if .Values.stalwart.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.stalwart.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.stalwart.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.stalwart.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "stalwart-mail-server.selectorLabels" . | nindent 6 }}
{{- end }}