# Stalwart Mail Server - Tiny Profile Configuration
# For demos, Raspberry Pi, and quick technical tests
# Single instance, optional PostgreSQL, blob storage mode available

global:
  profile: "tiny"
  storageClass: "default"  # or "local-path" for local development

stalwart:
  replicaCount: 1  # Single instance for demos
  image:
    repository: stalwartlabs/stalwart
    tag: "v0.12.1"
    pullPolicy: IfNotPresent
  
  # Recreate strategy for minimal resources
  strategy:
    type: Recreate
  
  # Minimal resources for Raspberry Pi / demo
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  
  persistence:
    enabled: true
    storageClass: ""  # Uses global.storageClass
    accessMode: ReadWriteOnce  # RWO for single instance
    size: 2Gi
  
  # Configuration storage (can be disabled for blob-only mode)
  configPersistence:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 512Mi
  
  # No anti-affinity needed for single instance
  affinity:
    podAntiAffinity:
      enabled: false
  
  # Basic security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  
  # Service configuration (NodePort for local testing)
  service:
    type: NodePort  # Use NodePort for local/demo environments
    ports:
      webadmin: 8080
      webadmin_ssl: 443
      smtp: 25
      submission: 587
      smtps: 465
      imap: 143
      imaps: 993
      pop3: 110
      pop3s: 995
      sieve: 4190
  
  # Basic health checks
  livenessProbe:
    httpGet:
      path: /healthz/live
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 10
    
  readinessProbe:
    httpGet:
      path: /healthz/ready
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 15
    timeoutSeconds: 5
  
  # Blob storage only mode (for ultra-fast demos)
  blobStorageOnly:
    enabled: false  # Set to true to disable PostgreSQL completely
    directory: "/opt/stalwart-mail/data"
  
  # Simple configuration for demos
  basicConfig:
    # Minimal SMTP settings
    smtp:
      hostname: "mail.local"
      banner: "Stalwart Mail Server Demo"
      relay:
        enabled: false
    
    # Basic IMAP settings
    imap:
      greeting: "Stalwart IMAP Demo Server"
    
    # Authentication - Admin password is auto-generated and shown in logs
    authentication:
      fallbackAdmin:
        enabled: true
        user: "admin"
        # Note: Password is auto-generated by Stalwart at startup
        # Check pod logs: kubectl logs <pod-name> | grep "administrator account"
        passwordFromLogs: true

# PostgreSQL Configuration (minimal, can be disabled)
postgresql:
  enabled: true  # Set to false for blob-storage-only mode
  auth:
    enablePostgresUser: true
    postgresPassword: ""  # Auto-generated but simple
    username: stalwart
    password: ""  # Auto-generated but simple
    database: stalwart
  
  primary:
    persistence:
      enabled: true
      storageClass: ""
      size: 2Gi  # Minimal storage for demos
    
    # Minimal resources for demo/RPI
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi
    
    # Basic security
    securityContext:
      enabled: true
      runAsNonRoot: true
      runAsUser: 999
      fsGroup: 999
  
  # Disable backup for demo profile
  backup:
    enabled: false

# Redis Configuration (disabled for tiny profile)
redis:
  enabled: false

# Network Policies (disabled for tiny profile)
networkPolicies:
  enabled: false

# Pod Security Standards (basic)
podSecurityPolicy:
  enabled: true
  policy: baseline  # Less restrictive for demos

# RBAC (minimal)
rbac:
  create: true
  serviceAccountName: stalwart-mail

# Monitoring (disabled for tiny profile)
monitoring:
  enabled: false
  prometheus:
    enabled: false
  grafana:
    enabled: false

# Ingress (disabled by default)
ingress:
  enabled: false

# External Secrets (disabled)
externalSecrets:
  enabled: false

# Backup (disabled for demos)
backup:
  enabled: false
  velero:
    enabled: false

# No autoscaling for single instance
autoscaling:
  enabled: false

# No Pod Disruption Budget needed
podDisruptionBudget:
  enabled: false

# No priority class for demos
priorityClass:
  create: false

# Demo-specific settings
demo:
  # Quick start mode
  quickStart:
    enabled: true
    createSampleUsers: true
    users:
      - username: "demo@mail.local"
        password: ""  # Will be auto-generated, check logs
        displayName: "Demo User"
      - username: "test@mail.local"  
        password: ""  # Will be auto-generated, check logs
        displayName: "Test User"
  
  # Sample domain configuration
  domains:
    - name: "mail.local"
      description: "Demo domain"
      dkim:
        enabled: false  # Disable for local demos
  
  # Development features
  development:
    enabled: true
    logLevel: "debug"
    skipTlsVerification: true
    allowInsecureAuth: true  # Only for demos!

# Special annotation for demo environments
annotations:
  stalwart.io/profile: "tiny"
  stalwart.io/demo-mode: "true"
  stalwart.io/warning: "THIS IS A DEMO CONFIGURATION - NOT FOR PRODUCTION USE"
  stalwart.io/admin-password: "check-pod-logs"

# Labels for identification
labels:
  environment: "demo"
  purpose: "testing"
  stalwart.io/profile: "tiny"